version: '3.1'
services:
  backend:
    build:
      dockerfile: docker/Dockerfile
    ports:
         - "8080:8080"
#         - "5432:5432"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/mydatabase
    networks:
      - spring-boot-postgres
    depends_on:
      postgres-db:
        condition: service_healthy


  postgres-db:
    image: postgres:15.0
    ports:
      - "5432:5432"
    environment:
       - POSTGRES_DB=mydatabase
       - POSTGRES_USER=myuser
       - POSTGRES_PASSWORD=secret
    volumes:
      - /var/lib/data:/var/lib/postgresql/data
    networks:
      - spring-boot-postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  spring-boot-postgres:
    driver: bridge

