#spring:
#  application:
#    name: CompanyCRUD
#
#  datasource:
#    url: jdbc:postgresql://localhost:5433/CompanyCRUD
#    username: postgres
#    password: postgresql
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
#    hikari:
#      schema: app_schema
  jpa:
    hibernate:
      ddl-auto: update