### post_manager
POST http://localhost:8080/api/managers/create
Content-Type: application/json

{
  "name": "Name5",
  "phone": "555 555 555"
}

### post_manager
POST http://localhost:8080/api/managers/create
Content-Type: application/json

{
  "name": "Name7",
  "phone": "700 700 700",
  "project": {
    "projectId": 1
  }
}

### update_manager
@update_id = 5
PUT http://localhost:8080/api/managers/update/{{update_id}}
Content-Type: application/json

{
  "project": {
    "projectId": 5
  }
}

### get_managers
GET http://localhost:8080/api/managers/getAllManagers

### find_by_id
@find_id = 1
GET http://localhost:8080/api/managers/find/{{find_id}}

### delete_manager
@delete_id = 4
DELETE http://localhost:8080/api/managers/delete/{{delete_id}}

